scoop bucket add extras;
scoop bucket add main;
scoop bucket add versions;
scoop bucket add nonportable;
scoop bucket add java;
scoop bucket add niaojin0407_scoop-niaojin https://github.com/niaojin0407/scoop-niaojin;

scoop install sharex;
scoop install vlc;
scoop install discord;
scoop install signal;
scoop install krita;
scoop install obs-studio;
scoop install anydesk;
scoop install qbittorrent;
scoop install stremio;
scoop install bulk-crap-uninstaller;
scoop install thunderbird;
scoop install streamlink;
scoop install brave;
scoop install git;
scoop install firefox;
scoop install kdeconnect;
scoop install figma;
scoop install eartrumpet;
scoop install vncviewer;
scoop install quick-picture-viewer;
scoop install onlyoffice-desktopeditors;
scoop install vcredist2022;
scoop install vscode;
scoop install 7zip;
scoop install nodejs-lts;
scoop install steam;
scoop install python310;
scoop install wireguard-np;
scoop install protonvpn-np;
scoop install wireguard-np;
scoop install oraclejre8;
scoop install corretto11-jdk;
scoop install parsec_win;
