winget install -e --id ShareX.ShareX;
winget install -e --id OBSProject.OBSStudio --force;
winget install -e --id VideoLAN.VLC --force;
winget install -e --id Discord.Discord;
winget install -e --id valinet.ExplorerPatcher.Prerelease;
winget install -e --id Valve.Steam;
winget install -e --id Microsoft.VisualStudioCode;
winget install -e --id OpenWhisperSystems.Signal;
winget install -e --id EclipseAdoptium.TemurinJRE.11;
winget install -e --id AdoptOpenJDK.OpenJDK.16;
winget install -e --id KDE.Krita;
winget install -e --id 7zip.7zip;
winget install -e --id ProtonTechnologies.ProtonVPN;
winget install -e --id OpenJS.NodeJS.LTS;
winget install -e --id yang991178.fluent-reader;
winget install -e --id qBittorrent.qBittorrent;
winget install -e --id Notepad++.Notepad++;
winget install -e --id Stremio.Stremio;
winget install -e --id Mozilla.Thunderbird;
winget install -e --id Streamlink.Streamlink;
winget install -e --id BraveSoftware.BraveBrowser;
winget install -e --id Git.Git;
winget install -e --id Python.Python.3;
winget install -e --id Mozilla.Firefox.DeveloperEdition;
winget install -e --id ONLYOFFICE.DesktopEditors;
winget install -e --id Oracle.JavaRuntimeEnvironment;
winget install -e --id WireGuard.WireGuard;
winget install -e --id KDE.KDEConnect;
winget install -e --id ModuleArt.QuickPictureViewer;
winget install -e --id RealVNC.VNCViewer;
winget install -e --id File-New-Project.EarTrumpet;
winget install -e --id Klocman.BulkCrapUninstaller;
winget install -e --id RustDesk.RustDesk;

wget https://github.com/alesimula/wsa_pacman/releases/download/v1.3.6/WSA-pacman-v1.3.6-installer.exe;
wget https://raw.githubusercontent.com/zachvlat/myuser.js/main/user.js;
wget https://github.com/keshavbhatt/WonderWall-Packaging/releases/download/v7.0/Wonderwall_7.0.Setup_x86_64.exe;
