winget install -e --id ShareX.ShareX;
winget install -e --id OBSProject.OBSStudio --force;
winget install -e --id VideoLAN.VLC --force;
winget install -e --id Discord.Discord;
winget install -e --id Valve.Steam;
winget install -e --id Microsoft.VisualStudioCode;
winget install -e --id OpenWhisperSystems.Signal;
winget install -e --id EclipseAdoptium.TemurinJRE.11;
winget install -e --id EclipseAdoptium.Temurin.11;
winget install -e --id KDE.Krita;
winget install -e --id 7zip.7zip;
winget install -e --id ProtonTechnologies.ProtonVPN;
winget install -e --id AnyDeskSoftwareGmbH.AnyDesk --force;
winget install -e --id OpenJS.NodeJS.LTS;
winget install -e --id qBittorrent.qBittorrent;
winget install -e --id Notepad++.Notepad++;
winget install -e --id Stremio.Stremio;
winget install -e --id Mozilla.Thunderbird;
winget install -e --id Streamlink.Streamlink;
winget install -e --id Parsec.Parsec --force;
winget install -e --id BraveSoftware.BraveBrowser;
winget install -e --id Git.Git;
winget install -e --id Python.Python.3;
winget install -e --id Mozilla.Firefox.DeveloperEdition;
winget install -e --id ONLYOFFICE.DesktopEditors;
winget install -e --id Oracle.JavaRuntimeEnvironment;
winget install -e --id WireGuard.WireGuard;
winget install -e --id KDE.KDEConnect;
winget install -e --id ModuleArt.QuickPictureViewer;
winget install -e --id RealVNC.VNCViewer;
winget install -e --id Figma.Figma;
winget install -e --id File-New-Project.EarTrumpet;
winget install -e --id Klocman.BulkCrapUninstaller;
winget install -e --id HeroicGamesLauncher.HeroicGamesLauncher;
winget install -e --id Playnite.Playnite;
winget install -e --id GOG.Galaxy;

wget https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x64.exe;
